Right (
  CTranslUnit [
    CDeclExt (
      CDecl [ CStorageSpec CTypedef, CTypeSpec CLongType, CTypeSpec CIntType ] 
            [ (Just (CDeclr (Just (Ident "ptrdiff_t" 412511821)) [] Nothing []), Nothing,Nothing) ]
    ),
    CDeclExt (
      CDecl [ CStorageSpec (CTypedef), CTypeSpec (CLongType), CTypeSpec (CUnsigType), CTypeSpec (CIntType) ] 
            [ (Just (CDeclr (Just (Ident "size_t" 213839698)) [] Nothing []),Nothing,Nothing) ]
    ),
    CDeclExt (
      CDecl [ CStorageSpec (CTypedef),CTypeSpec (CIntType) ] 
            [(Just (CDeclr (Just (Ident "wchar_t" 207053289)) [] Nothing []),Nothing,Nothing)]
    ),
    CDeclExt (
      CDecl [ CStorageSpec (CTypedef), CTypeSpec (CSignedType), CTypeSpec (CCharType) ] 
            [ (Just (CDeclr (Just (Ident "int8_t" 119370184)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CShortType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "int16_t" 106587935)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CLongType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "int32_t" 110782235)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CLongType),CTypeSpec (CLongType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "int64_t" 117073693)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CUnsigType),CTypeSpec (CCharType)] [(Just (CDeclr (Just (Ident "uint8_t" 246998189)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CShortType),CTypeSpec (CUnsigType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "uint16_t" 489918502)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CLongType),CTypeSpec (CUnsigType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "uint32_t" 489917992)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CLongType),CTypeSpec (CLongType),CTypeSpec (CUnsigType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "uint64_t" 489918251)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CSignedType),CTypeSpec (CCharType)] [(Just (CDeclr (Just (Ident "int_least8_t" 420316873)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CShortType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "int_least16_t" 375604157)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CLongType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "int_least32_t" 375538877)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CLongType),CTypeSpec (CLongType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "int_least64_t" 375572029)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CUnsigType),CTypeSpec (CCharType)] [(Just (CDeclr (Just (Ident "uint_least8_t" 381904443)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CShortType),CTypeSpec (CUnsigType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "uint_least16_t" 295821350)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CLongType),CTypeSpec (CUnsigType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "uint_least32_t" 287465510)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CLongType),CTypeSpec (CLongType),CTypeSpec (CUnsigType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "uint_least64_t" 291708966)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "int_fast8_t" 448223239 )) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "int_fast16_t" 422708096)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "int_fast32_t" 422707586 )) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef),CTypeSpec (CLongType),CTypeSpec (CLongType),CTypeSpec (CIntType)] [(Just (CDeclr (Just (Ident "int_fast64_t" 422707845)) [] Nothing []),Nothing,Nothing)]),
    CDeclExt (CDecl [CStorageSpec (CTypedef ),CTypeSpec (CUnsigType ),CTypeSpec (CIntType )] [(Just (CDeclr (Just (Ident "uint_fast8_t" 464258248 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (CDecl [CStorageSpec (CTypedef ),CTypeSpec (CUnsigType ),CTypeSpec (CIntType )] [(Just (CDeclr (Just (Ident "uint_fast16_t" 419545532 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (CDecl [CStorageSpec (CTypedef ),CTypeSpec (CUnsigType ),CTypeSpec (CIntType )] [(Just (CDeclr (Just (Ident "uint_fast32_t" 419480252 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (CDecl [CStorageSpec (CTypedef ),CTypeSpec (CLongType ),CTypeSpec (CLongType ),CTypeSpec (CUnsigType ),CTypeSpec (CIntType )] [(Just (CDeclr (Just (Ident "uint_fast64_t" 419513404 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (CDecl [CStorageSpec (CTypedef ),CTypeSpec (CLongType ),CTypeSpec (CIntType )] [(Just (CDeclr (Just (Ident "intptr_t" 481636573 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (CDecl [CStorageSpec (CTypedef ),CTypeSpec (CLongType ),CTypeSpec (CUnsigType ),CTypeSpec (CIntType )] [(Just (CDeclr (Just (Ident "uintptr_t" 446197721 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (CDecl [CStorageSpec (CTypedef ),CTypeSpec (CLongType ),CTypeSpec (CLongType ),CTypeSpec (CIntType )] [(Just (CDeclr (Just (Ident "intmax_t" 475345866 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (CDecl [CStorageSpec (CTypedef ),CTypeSpec (CLongType ),CTypeSpec (CLongType ),CTypeSpec (CUnsigType ),CTypeSpec (CIntType )] [(Just (CDeclr (Just (Ident "uintmax_t" 446293590 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (CDecl [CTypeSpec (CEnumType (CEnum (Just (Ident "vga_color" 435399755 )) (Just [(Ident "VGA_COLOR_BLACK" 260513068 ,Just (CConst (CIntConst 0 ))),(Ident "VGA_COLOR_BLUE" 259284544 ,Just (CConst (CIntConst 1 ))),(Ident "VGA_COLOR_GREEN" 273227312 ,Just (CConst (CIntConst 2 ))),(Ident "VGA_COLOR_CYAN" 286565036 ,Just (CConst (CIntConst 3 ))),(Ident "VGA_COLOR_RED" 244857775 ,Just (CConst (CIntConst 4 ))),(Ident "VGA_COLOR_MAGENTA" 413834867 ,Just (CConst (CIntConst 5 ))),(Ident "VGA_COLOR_BROWN" 273147706 ,Just (CConst (CIntConst 6 ))),(Ident "VGA_COLOR_LIGHT_GREY" 373115129 ,Just (CConst (CIntConst 7 ))),(Ident "VGA_COLOR_DARK_GREY" 388170767 ,Just (CConst (CIntConst 8 ))),(Ident "VGA_COLOR_LIGHT_BLUE" 331433460 ,Just (CConst (CIntConst 9 ))),(Ident "VGA_COLOR_LIGHT_GREEN" 331172167 ,Just (CConst (CIntConst 10 ))),(Ident "VGA_COLOR_LIGHT_CYAN" 349981813 ,Just (CConst (CIntConst 11 ))),(Ident "VGA_COLOR_LIGHT_RED" 454886020 ,Just (CConst (CIntConst 12 ))),(Ident "VGA_COLOR_LIGHT_MAGENTA" 332278477 ,Just (CConst (CIntConst 13 ))),(Ident "VGA_COLOR_LIGHT_BROWN" 369084738 ,Just (CConst (CIntConst 14 ))),(Ident "VGA_COLOR_WHITE" 252372404 ,Just (CConst (CIntConst 15 )))]) [] ) )] [] ),
    CFDefExt (CFunDef [CStorageSpec (CStatic ),CFunSpec (CInlineQual ),CTypeSpec (CTypeDef (Ident "uint8_t" 246998189 ) )] (CDeclr (Just (Ident "vga_entry_color" 409686848 )) [CFunDeclr (Right ([CDecl [CTypeSpec (CEnumType (CEnum (Just (Ident "vga_color" 435399755 )) Nothing [] ) )] [(Just (CDeclr (Just (Ident "fg" 13286 )) [] Nothing [] ),Nothing,Nothing)] ,CDecl [CTypeSpec (CEnumType (CEnum (Just (Ident "vga_color" 435399755 )) Nothing [] ) )] [(Just (CDeclr (Just (Ident "bg" 13282 )) [] Nothing [] ),Nothing,Nothing)] ],False)) [] ] Nothing [] ) [] (CCompound [] [CBlockStmt (CReturn (Just (CBinary COrOp (CVar (Ident "fg" 13286 ) ) (CBinary CShlOp (CVar (Ident "bg" 13282 ) ) (CConst (CIntConst 4 )) ) )) )] ) ),
    CFDefExt (CFunDef [CStorageSpec (CStatic ),CFunSpec (CInlineQual ),CTypeSpec (CTypeDef (Ident "uint16_t" 489918502 ) )] (CDeclr (Just (Ident "vga_entry" 441822164 )) [CFunDeclr (Right ([CDecl [CTypeSpec (CUnsigType ),CTypeSpec (CCharType )] [(Just (CDeclr (Just (Ident "uc" 12789 )) [] Nothing [] ),Nothing,Nothing)] ,CDecl [CTypeSpec (CTypeDef (Ident "uint8_t" 246998189 ) )] [(Just (CDeclr (Just (Ident "color" 234567765 )) [] Nothing [] ),Nothing,Nothing)] ],False)) [] ] Nothing [] ) [] (CCompound [] [CBlockStmt (CReturn (Just (CBinary COrOp (CCast (CDecl [CTypeSpec (CTypeDef (Ident "uint16_t" 489918502 ) )] [] ) (CVar (Ident "uc" 12789 ) ) ) (CBinary CShlOp (CCast (CDecl [CTypeSpec (CTypeDef (Ident "uint16_t" 489918502 ) )] [] ) (CVar (Ident "color" 234567765 ) ) ) (CConst (CIntConst 8 )) ) )) )] ) ),
    CFDefExt (CFunDef [CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] (CDeclr (Just (Ident "strlen" 228389336 )) [CFunDeclr (Right ([CDecl [CTypeQual (CConstQual ),CTypeSpec (CCharType )] [(Just (CDeclr (Just (Ident "str" 1882739 )) [CPtrDeclr [] ] Nothing [] ),Nothing,Nothing)] ],False)) [] ] Nothing [] ) [] (CCompound [] [CBlockDecl (CDecl [CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "len" 1815276 )) [] Nothing [] ),Just (CInitExpr (CConst (CIntConst 0 )) ),Nothing)] ),CBlockStmt (CWhile (CIndex (CVar (Ident "str" 1882739 ) ) (CVar (Ident "len" 1815276 ) ) ) (CExpr (Just (CUnary CPostIncOp (CVar (Ident "len" 1815276 ) ) )) ) False ),CBlockStmt (CReturn (Just (CVar (Ident "len" 1815276 ) )) )] ) ),
    CDeclExt (CDecl [CStorageSpec (CStatic ),CTypeQual (CConstQual ),CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "VGA_WIDTH" 377587957 )) [] Nothing [] ),Just (CInitExpr (CConst (CIntConst 80 )) ),Nothing)] ),
    CDeclExt (CDecl [CStorageSpec (CStatic ),CTypeQual (CConstQual ),CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "VGA_HEIGHT" 350417126 )) [] Nothing [] ),Just (CInitExpr (CConst (CIntConst 25 )) ),Nothing)] ),
    CDeclExt (CDecl [CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "terminal_row" 441525180 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (CDecl [CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "terminal_column" 420270897 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (CDecl [CTypeSpec (CTypeDef (Ident "uint8_t" 246998189 ) )] [(Just (CDeclr (Just (Ident "terminal_color" 418469291 )) [] Nothing [] ),Nothing,Nothing)] ),
    CDeclExt (
      CDecl [
        CTypeSpec (CTypeDef (Ident "uint16_t" 489918502))
      ] [ (Just (CDeclr (Just (Ident "terminal_buffer" 407850658)) [CPtrDeclr []] Nothing []),Nothing,Nothing) ]
    ),
    CFDefExt (CFunDef [CTypeSpec (CVoidType)] (CDeclr (Just (Ident "terminal_initialize" 373477785)) [CFunDeclr (Right ([CDecl [CTypeSpec (CVoidType)] []],False)) []] Nothing []) [] (CCompound [] [CBlockStmt (CExpr (Just (CAssign CAssignOp (CVar (Ident "terminal_row" 441525180)) (CConst (CIntConst 0))))),CBlockStmt (CExpr (Just (CAssign CAssignOp (CVar (Ident "terminal_column" 420270897)) (CConst (CIntConst 0))))),CBlockStmt (CExpr (Just (CAssign CAssignOp (CVar (Ident "terminal_color" 418469291)) (CCall (CVar (Ident "vga_entry_color" 409686848)) [CVar (Ident "VGA_COLOR_LIGHT_GREY" 373115129),CVar (Ident "VGA_COLOR_BLACK" 260513068)])))),CBlockStmt (CExpr (Just (CAssign CAssignOp (CVar (Ident "terminal_buffer" 407850658)) (CCast (CDecl [CTypeSpec (CTypeDef (Ident "uint16_t" 489918502) )] [(Just (CDeclr Nothing [CPtrDeclr []] Nothing [] (OnlyPos <no file> (<no file>,-1))),Nothing,Nothing)]) (CConst (CIntConst 0xb8000)))))),CBlockStmt (CFor (Right (CDecl [CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "y" 121 )) [] Nothing [] ),Just (CInitExpr (CConst (CIntConst 0 )) ),Nothing)] )) (Just (CBinary CLeOp (CVar (Ident "y" 121 ) ) (CVar (Ident "VGA_HEIGHT" 350417126 ) ) )) (Just (CUnary CPostIncOp (CVar (Ident "y" 121 ) ) )) (CCompound [] [CBlockStmt (CFor (Right (CDecl [CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "x" 120 )) [] Nothing [] ),Just (CInitExpr (CConst (CIntConst 0 )) ),Nothing)] )) (Just (CBinary CLeOp (CVar (Ident "x" 120 ) ) (CVar (Ident "VGA_WIDTH" 377587957 ) ) )) (Just (CUnary CPostIncOp (CVar (Ident "x" 120 ) ) )) (CCompound [] [CBlockDecl (CDecl [CTypeQual (CConstQual ),CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "index" 213465057 )) [] Nothing [] ),Just (CInitExpr (CBinary CAddOp (CBinary CMulOp (CVar (Ident "y" 121 ) ) (CVar (Ident "VGA_WIDTH" 377587957 ) ) ) (CVar (Ident "x" 120 ) ) ) ),Nothing)] ),CBlockStmt (CExpr (Just (CAssign CAssignOp (CIndex (CVar (Ident "terminal_buffer" 407850658 ) ) (CVar (Ident "index" 213465057 ) ) ) (CCall (CVar (Ident "vga_entry" 441822164 ) ) [CConst (CCharConst ' ' ),CVar (Ident "terminal_color" 418469291 ) ] ) )) )] ) )] ) )] ) ),
    CFDefExt (CFunDef [CTypeSpec (CVoidType )] (CDeclr (Just (Ident "terminal_setcolor" 401202321 )) [CFunDeclr (Right ([CDecl [CTypeSpec (CTypeDef (Ident "uint8_t" 246998189 ) )] [(Just (CDeclr (Just (Ident "color" 234567765 )) [] Nothing [] ),Nothing,Nothing)] ],False)) [] ] Nothing [] ) [] (CCompound [] [CBlockStmt (CExpr (Just (CAssign CAssignOp (CVar (Ident "terminal_color" 418469291 ) ) (CVar (Ident "color" 234567765 ) ) )) )] ) ),
    CFDefExt (CFunDef [CTypeSpec (CVoidType )] (CDeclr (Just (Ident "terminal_putentryat" 409799450 )) [CFunDeclr (Right ([CDecl [CTypeSpec (CCharType )] [(Just (CDeclr (Just (Ident "c" 99 )) [] Nothing [] ),Nothing,Nothing)] ,CDecl [CTypeSpec (CTypeDef (Ident "uint8_t" 246998189 ) )] [(Just (CDeclr (Just (Ident "color" 234567765 )) [] Nothing [] ),Nothing,Nothing)] ,CDecl [CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "x" 120 )) [] Nothing [] ),Nothing,Nothing)] ,CDecl [CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "y" 121 )) [] Nothing [] ),Nothing,Nothing)] ],False)) [] ] Nothing [] ) [] (CCompound [] [CBlockDecl (CDecl [CTypeQual (CConstQual ),CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "index" 213465057 )) [] Nothing [] ),Just (CInitExpr (CBinary CAddOp (CBinary CMulOp (CVar (Ident "y" 121 ) ) (CVar (Ident "VGA_WIDTH" 377587957 ) ) ) (CVar (Ident "x" 120 ) ) ) ),Nothing)] ),CBlockStmt (CExpr (Just (CAssign CAssignOp (CIndex (CVar (Ident "terminal_buffer" 407850658 ) ) (CVar (Ident "index" 213465057 ) ) ) (CCall (CVar (Ident "vga_entry" 441822164 ) ) [CVar (Ident "c" 99 ) ,CVar (Ident "color" 234567765 ) ] ) )) )] ) ),
    CFDefExt (CFunDef [CTypeSpec (CVoidType )] (CDeclr (Just (Ident "terminal_putchar" 407574303 )) [CFunDeclr (Right ([CDecl [CTypeSpec (CCharType )] [(Just (CDeclr (Just (Ident "c" 99 )) [] Nothing [] ),Nothing,Nothing)] ],False)) [] ] Nothing [] ) [] (CCompound [] [CBlockStmt (CExpr (Just (CCall (CVar (Ident "terminal_putentryat" 409799450 ) ) [CVar (Ident "c" 99 ) ,CVar (Ident "terminal_color" 418469291 ) ,CVar (Ident "terminal_column" 420270897 ) ,CVar (Ident "terminal_row" 441525180 ) ] )) ),CBlockStmt (CIf (CBinary CEqOp (CUnary CPreIncOp (CVar (Ident "terminal_column" 420270897 ) ) ) (CVar (Ident "VGA_WIDTH" 377587957 ) ) ) (CCompound [] [CBlockStmt (CExpr (Just (CAssign CAssignOp (CVar (Ident "terminal_column" 420270897 ) ) (CConst (CIntConst 0 )) )) ),CBlockStmt (CIf (CBinary CEqOp (CUnary CPreIncOp (CVar (Ident "terminal_row" 441525180 ) ) ) (CVar (Ident "VGA_HEIGHT" 350417126 ) ) ) (CExpr (Just (CAssign CAssignOp (CVar (Ident "terminal_row" 441525180 ) ) (CConst (CIntConst 0 )) )) ) Nothing )] ) Nothing )] ) ),
    CFDefExt (CFunDef [CTypeSpec (CVoidType)] (CDeclr (Just (Ident "terminal_write" 412227888)) [CFunDeclr (Right ([CDecl [CTypeQual (CConstQual),CTypeSpec (CCharType)] [(Just (CDeclr (Just (Ident "data" 205336804)) [CPtrDeclr []] Nothing [] ),Nothing,Nothing)] ,CDecl [CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "size" 213824755 )) [] Nothing [] ),Nothing,Nothing)] ],False)) [] ] Nothing [] ) [] (CCompound [] [CBlockStmt (CFor (Right (CDecl [CTypeSpec (CTypeDef (Ident "size_t" 213839698 ) )] [(Just (CDeclr (Just (Ident "i" 105 )) [] Nothing [] ),Just (CInitExpr (CConst (CIntConst 0 )) ),Nothing)] )) (Just (CBinary CLeOp (CVar (Ident "i" 105 ) ) (CVar (Ident "size" 213824755 ) ) )) (Just (CUnary CPostIncOp (CVar (Ident "i" 105 ) ) )) (CExpr (Just (CCall (CVar (Ident "terminal_putchar" 407574303 ) ) [CIndex (CVar (Ident "data" 205336804 ) ) (CVar (Ident "i" 105 ) ) ] )) ) )] ) ),
    CFDefExt (CFunDef [CTypeSpec (CVoidType)] (CDeclr (Just (Ident "terminal_writestring" 338333218)) [CFunDeclr (Right ([CDecl [CTypeQual (CConstQual),CTypeSpec (CCharType)] [(Just (CDeclr (Just (Ident "data" 205336804)) [CPtrDeclr []] Nothing []),Nothing,Nothing)]],False)) []] Nothing []) [] (CCompound [] [CBlockStmt (CExpr (Just (CCall (CVar (Ident "terminal_write" 412227888)) [CVar (Ident "data" 205336804),CCall (CVar (Ident "strlen" 228389336)) [CVar (Ident "data" 205336804 ) ] ] )) )] ) ),
    CFDefExt (CFunDef [CTypeSpec (CVoidType)] (CDeclr (Just (Ident "kernel_main" 464543281)) [CFunDeclr (Right ([CDecl [CTypeSpec (CVoidType)] []],False)) []] Nothing []) [] (CCompound [] [CBlockStmt (CExpr (Just (CCall (CVar (Ident "terminal_initialize" 373477785)) []))),CBlockStmt (CExpr (Just (CCall (CVar (Ident "terminal_writestring" 338333218)) [CConst (CStrConst "Hello, kernel World!\n")])))]))])

