name: Haskell CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.8.1'
        cabal-version: '3.0'
    - name: Install dependencies
      working-directory: radon
      run: |
        cabal update
        cabal install --only-dependencies
    - name: Build
      working-directory: radon
      run: |
        cabal configure --enable-tests
        cabal build
    - name: Run tests
      working-directory: radon
      run: cabal test
